[2025-07-03 17:11:08,572: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-03 17:11:08,576: INFO/MainProcess] mingle: searching for neighbors
[2025-07-03 17:11:09,587: INFO/MainProcess] mingle: all alone
[2025-07-03 17:11:09,603: INFO/MainProcess] celery@ecd8b405aec1 ready.
[2025-07-03 17:11:23,111: INFO/MainProcess] Task create_task[9324affa-7460-4cff-93e8-13e2e9673b13] received
[2025-07-03 17:11:23,757: INFO/MainProcess] Task create_task[06c117f1-e65e-40fb-98d1-af0a8067dea2] received
[2025-07-03 17:11:24,726: INFO/MainProcess] Task create_task[6b4ac125-84c7-4dea-9ab1-957ffc9964cd] received
[2025-07-03 17:11:33,176: INFO/ForkPoolWorker-7] Task create_task[9324affa-7460-4cff-93e8-13e2e9673b13] succeeded in 10.059231280000063s: True
[2025-07-03 17:11:43,778: INFO/ForkPoolWorker-8] Task create_task[06c117f1-e65e-40fb-98d1-af0a8067dea2] succeeded in 20.017599623000024s: True
[2025-07-03 17:11:54,868: INFO/ForkPoolWorker-1] Task create_task[6b4ac125-84c7-4dea-9ab1-957ffc9964cd] succeeded in 30.01431726599992s: True
[2025-07-03 17:13:31,193: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-03 17:13:31,230: INFO/MainProcess] mingle: searching for neighbors
[2025-07-03 17:13:32,272: INFO/MainProcess] mingle: all alone
[2025-07-03 17:13:32,361: INFO/MainProcess] celery@e6f06ce1ebc5 ready.
[2025-07-03 17:13:33,735: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-03 17:19:49,272: INFO/MainProcess] Task create_task[cf5e858b-920d-475f-af92-a9082413ed3c] received
[2025-07-03 17:19:49,295: INFO/ForkPoolWorker-7] Task create_task[cf5e858b-920d-475f-af92-a9082413ed3c] succeeded in 0.013278678000006039s: True
[2025-07-03 17:20:07,401: INFO/MainProcess] Task create_task[29e71be8-b88d-4882-abcc-b880f1bce803] received
[2025-07-03 17:20:07,406: INFO/ForkPoolWorker-7] Task create_task[29e71be8-b88d-4882-abcc-b880f1bce803] succeeded in 0.0017743210000844556s: True
[2025-07-03 17:20:20,449: INFO/MainProcess] Task create_task[480a88c4-d7ea-4cee-8e06-d66170b598e4] received
[2025-07-03 17:20:30,453: INFO/ForkPoolWorker-7] Task create_task[480a88c4-d7ea-4cee-8e06-d66170b598e4] succeeded in 10.001336881000043s: True
[2025-07-03 17:23:17,871: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-03 17:23:17,880: INFO/MainProcess] mingle: searching for neighbors
[2025-07-03 17:23:18,890: INFO/MainProcess] mingle: all alone
[2025-07-03 17:23:18,903: INFO/MainProcess] celery@55aa5f7cc4de ready.
[2025-07-03 17:23:22,736: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-03 17:23:30,436: INFO/MainProcess] Task create_task[d502db9f-f0b7-4aef-943c-7fca4212b931] received
[2025-07-03 17:23:40,461: INFO/ForkPoolWorker-7] Task create_task[d502db9f-f0b7-4aef-943c-7fca4212b931] succeeded in 10.008478991999937s: True
[2025-07-03 17:23:41,404: INFO/MainProcess] Task create_task[6355ebd4-d183-4d1d-a67e-98c5f637f6fc] received
[2025-07-03 17:23:41,408: INFO/ForkPoolWorker-7] Task create_task[6355ebd4-d183-4d1d-a67e-98c5f637f6fc] succeeded in 0.0014030770000772463s: True
[2025-07-04 14:03:46,214: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-04 14:03:46,216: INFO/MainProcess] mingle: searching for neighbors
[2025-07-04 14:03:47,222: INFO/MainProcess] mingle: all alone
[2025-07-04 14:03:47,230: INFO/MainProcess] celery@774bd2f643e3 ready.
[2025-07-04 14:03:51,078: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-04 14:04:04,266: INFO/MainProcess] Task create_task[c996e9b5-f406-4853-a89c-dbc5bc1eba1a] received
[2025-07-04 14:04:14,263: INFO/MainProcess] Task create_task[4214d957-186d-46a3-8929-0bf3b693ebb4] received
[2025-07-04 14:04:14,267: INFO/ForkPoolWorker-15] Task create_task[c996e9b5-f406-4853-a89c-dbc5bc1eba1a] succeeded in 10.002234583000003s: True
[2025-07-04 14:04:20,361: INFO/MainProcess] Task create_task[4f85faed-7379-492e-811d-03b8bdfc009f] received
[2025-07-04 14:04:34,267: INFO/ForkPoolWorker-16] Task create_task[4214d957-186d-46a3-8929-0bf3b693ebb4] succeeded in 20.002517799999993s: True
[2025-07-04 14:04:50,361: INFO/ForkPoolWorker-15] Task create_task[4f85faed-7379-492e-811d-03b8bdfc009f] succeeded in 30.000843664s: True
[2025-07-05 12:36:00,838: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 12:36:00,842: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 12:36:01,848: INFO/MainProcess] mingle: all alone
[2025-07-05 12:36:01,857: INFO/MainProcess] celery@0d4ba274b8e1 ready.
[2025-07-05 12:36:04,055: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 12:43:26,215: INFO/MainProcess] Task procesar_receta_task[8bdce513-0866-410a-aba2-3072ad59e230] received
[2025-07-05 12:43:26,217: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 12:43:26,880: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[2025-07-05 12:43:27,128: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[2025-07-05 12:43:27,416: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[2025-07-05 12:43:27,581: WARNING/ForkPoolWorker-14] WARNING: [TikTok] 7518837827455552790: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[2025-07-05 12:43:28,210: WARNING/ForkPoolWorker-14] ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:43:28,217: WARNING/ForkPoolWorker-14] --- Logging error ---
[2025-07-05 12:43:28,220: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:43:28,221: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,221: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,221: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,222: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,222: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,222: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1280, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,222: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
[2025-07-05 12:43:28,223: WARNING/ForkPoolWorker-14] yt_dlp.utils.RegexNotFoundError: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:43:28,223: WARNING/ForkPoolWorker-14] 
During handling of the above exception, another exception occurred:
[2025-07-05 12:43:28,223: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:43:28,224: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,224: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,224: WARNING/ForkPoolWorker-14]   File "/usr/src/app/worker.py", line 20, in procesar_receta_task
    procesar_receta(url)
[2025-07-05 12:43:28,224: WARNING/ForkPoolWorker-14]   File "/usr/src/app/model_mistral_tiktok.py", line 105, in procesar_receta
    titulo, descripcion, thumbnail = download_tiktok_video(url, f'./videos/video{timestamp}.mp4')
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,225: WARNING/ForkPoolWorker-14]   File "/usr/src/app/model_mistral_tiktok.py", line 33, in download_tiktok_video
    info = ydl.extract_info(url, download=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,225: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,225: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    self.report_error(str(e), e.format_traceback())
[2025-07-05 12:43:28,225: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
[2025-07-05 12:43:28,226: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble
    raise DownloadError(message, exc_info)
[2025-07-05 12:43:28,226: WARNING/ForkPoolWorker-14] yt_dlp.utils.DownloadError: ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:43:28,226: WARNING/ForkPoolWorker-14] 
During handling of the above exception, another exception occurred:
[2025-07-05 12:43:28,226: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:43:28,227: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,227: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,227: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
          ^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,228: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 695, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,228: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
    r = super().formatException(ei)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,228: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 645, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2025-07-05 12:43:28,228: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,229: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 690, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,229: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
[2025-07-05 12:43:28,229: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,229: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 366, in _get_code_position
    positions_gen = code.co_positions()
                    ^^^^^^^^^^^^^^^^^
[2025-07-05 12:43:28,230: WARNING/ForkPoolWorker-14] AttributeError: '_Code' object has no attribute 'co_positions'
[2025-07-05 12:43:28,230: WARNING/ForkPoolWorker-14] Call stack:
[2025-07-05 12:43:28,237: WARNING/ForkPoolWorker-14]   File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
[2025-07-05 12:43:28,237: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
[2025-07-05 12:43:28,237: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
[2025-07-05 12:43:28,237: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
[2025-07-05 12:43:28,238: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
[2025-07-05 12:43:28,238: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-07-05 12:43:28,238: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-07-05 12:43:28,238: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
[2025-07-05 12:43:28,239: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-07-05 12:43:28,239: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2025-07-05 12:43:28,239: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
    worker.start()
[2025-07-05 12:43:28,239: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2025-07-05 12:43:28,240: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-07-05 12:43:28,240: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-07-05 12:43:28,240: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2025-07-05 12:43:28,240: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-07-05 12:43:28,241: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-07-05 12:43:28,241: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2025-07-05 12:43:28,241: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
    return super()._create_worker_process(i)
[2025-07-05 12:43:28,241: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2025-07-05 12:43:28,242: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2025-07-05 12:43:28,242: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2025-07-05 12:43:28,242: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2025-07-05 12:43:28,242: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2025-07-05 12:43:28,243: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2025-07-05 12:43:28,243: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2025-07-05 12:43:28,243: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-07-05 12:43:28,243: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-07-05 12:43:28,244: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-07-05 12:43:28,244: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
[2025-07-05 12:43:28,244: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(
[2025-07-05 12:43:28,244: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
[2025-07-05 12:43:28,245: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
    self._log_error(task, req, einfo)
[2025-07-05 12:43:28,245: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
    logger.log(policy.severity, policy.format.strip(), context,
[2025-07-05 12:43:28,245: WARNING/ForkPoolWorker-14] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
Arguments: {'hostname': 'celery@0d4ba274b8e1', 'id': '8bdce513-0866-410a-aba2-3072ad59e230', 'name': 'procesar_receta_task', 'exc': "DownloadError('ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper\n    return func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info\n    ie_result = ie.extract(url)\n                ^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract\n    ie_result = self._real_extract(url)\n                ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract\n    sigi_data = self._get_sigi_state(webpage, video_id)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state\n    return self._search_json(\n           ^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1280, in _search_json\n    json_string = self._search_regex(\n                  ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex\n    raise RegexNotFoundError(\'Unable to extract %s\' % _name)\nyt_dlp.utils.RegexNotFoundError: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/worker.py", line 20, in procesar_receta_task\n    procesar_receta(url)\n  File "/usr/src/app/model_mistral_tiktok.py", line 105, in procesar_receta\n    titulo, descripcion, thumbnail = download_tiktok_video(url, f\'./videos/video{timestamp}.mp4\')\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/model_mistral_tiktok.py", line 33, in download_tiktok_video\n    info = ydl.extract_info(url, download=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info\n    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper\n    self.report_error(str(e), e.format_traceback())\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error\n    self.trouble(f\'{self._format_err("ERROR:", self.Styles.ERROR)} {message}\', *args, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble\n    raise DownloadError(message, exc_info)\nyt_dlp.utils.DownloadError: ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n', 'args': "['https://www.tiktok.com/@comiendobienn/video/7518837827455552790']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
[2025-07-05 12:48:47,036: INFO/MainProcess] Task procesar_receta_task[ceee7eef-e888-414f-a8db-92af6d4ef087] received
[2025-07-05 12:48:47,037: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 12:48:47,452: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[2025-07-05 12:48:47,708: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[2025-07-05 12:48:47,926: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[2025-07-05 12:48:48,104: WARNING/ForkPoolWorker-14] WARNING: [TikTok] 7518837827455552790: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[2025-07-05 12:48:48,799: WARNING/ForkPoolWorker-14] ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:48:48,803: WARNING/ForkPoolWorker-14] --- Logging error ---
[2025-07-05 12:48:48,805: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:48:48,805: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,805: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,806: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,806: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,806: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,806: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1280, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,807: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
[2025-07-05 12:48:48,807: WARNING/ForkPoolWorker-14] yt_dlp.utils.RegexNotFoundError: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:48:48,807: WARNING/ForkPoolWorker-14] 
During handling of the above exception, another exception occurred:
[2025-07-05 12:48:48,807: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:48:48,808: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,808: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,808: WARNING/ForkPoolWorker-14]   File "/usr/src/app/worker.py", line 20, in procesar_receta_task
    procesar_receta(url)
[2025-07-05 12:48:48,809: WARNING/ForkPoolWorker-14]   File "/usr/src/app/model_mistral_tiktok.py", line 105, in procesar_receta
    titulo, descripcion, thumbnail = download_tiktok_video(url, f'./videos/video{timestamp}.mp4')
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,809: WARNING/ForkPoolWorker-14]   File "/usr/src/app/model_mistral_tiktok.py", line 33, in download_tiktok_video
    info = ydl.extract_info(url, download=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,809: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,809: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    self.report_error(str(e), e.format_traceback())
[2025-07-05 12:48:48,810: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
[2025-07-05 12:48:48,810: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble
    raise DownloadError(message, exc_info)
[2025-07-05 12:48:48,810: WARNING/ForkPoolWorker-14] yt_dlp.utils.DownloadError: ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:48:48,810: WARNING/ForkPoolWorker-14] 
During handling of the above exception, another exception occurred:
[2025-07-05 12:48:48,811: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:48:48,811: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,811: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,812: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
          ^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,812: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 695, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,812: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
    r = super().formatException(ei)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,812: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 645, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2025-07-05 12:48:48,813: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,813: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 690, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,813: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
[2025-07-05 12:48:48,813: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,814: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 366, in _get_code_position
    positions_gen = code.co_positions()
                    ^^^^^^^^^^^^^^^^^
[2025-07-05 12:48:48,814: WARNING/ForkPoolWorker-14] AttributeError: '_Code' object has no attribute 'co_positions'
[2025-07-05 12:48:48,814: WARNING/ForkPoolWorker-14] Call stack:
[2025-07-05 12:48:48,815: WARNING/ForkPoolWorker-14]   File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
[2025-07-05 12:48:48,815: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
[2025-07-05 12:48:48,815: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
[2025-07-05 12:48:48,815: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
[2025-07-05 12:48:48,816: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
[2025-07-05 12:48:48,816: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-07-05 12:48:48,816: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-07-05 12:48:48,816: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
[2025-07-05 12:48:48,817: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-07-05 12:48:48,817: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2025-07-05 12:48:48,817: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
    worker.start()
[2025-07-05 12:48:48,818: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2025-07-05 12:48:48,818: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-07-05 12:48:48,818: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-07-05 12:48:48,818: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2025-07-05 12:48:48,819: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-07-05 12:48:48,819: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-07-05 12:48:48,819: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2025-07-05 12:48:48,819: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
    return super()._create_worker_process(i)
[2025-07-05 12:48:48,820: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2025-07-05 12:48:48,820: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2025-07-05 12:48:48,820: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2025-07-05 12:48:48,820: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2025-07-05 12:48:48,821: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2025-07-05 12:48:48,821: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2025-07-05 12:48:48,821: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2025-07-05 12:48:48,821: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-07-05 12:48:48,822: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-07-05 12:48:48,822: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-07-05 12:48:48,822: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
[2025-07-05 12:48:48,822: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(
[2025-07-05 12:48:48,823: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
[2025-07-05 12:48:48,823: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
    self._log_error(task, req, einfo)
[2025-07-05 12:48:48,823: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
    logger.log(policy.severity, policy.format.strip(), context,
[2025-07-05 12:48:48,824: WARNING/ForkPoolWorker-14] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
Arguments: {'hostname': 'celery@0d4ba274b8e1', 'id': 'ceee7eef-e888-414f-a8db-92af6d4ef087', 'name': 'procesar_receta_task', 'exc': "DownloadError('ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper\n    return func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info\n    ie_result = ie.extract(url)\n                ^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract\n    ie_result = self._real_extract(url)\n                ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract\n    sigi_data = self._get_sigi_state(webpage, video_id)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state\n    return self._search_json(\n           ^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1280, in _search_json\n    json_string = self._search_regex(\n                  ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex\n    raise RegexNotFoundError(\'Unable to extract %s\' % _name)\nyt_dlp.utils.RegexNotFoundError: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/worker.py", line 20, in procesar_receta_task\n    procesar_receta(url)\n  File "/usr/src/app/model_mistral_tiktok.py", line 105, in procesar_receta\n    titulo, descripcion, thumbnail = download_tiktok_video(url, f\'./videos/video{timestamp}.mp4\')\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/model_mistral_tiktok.py", line 33, in download_tiktok_video\n    info = ydl.extract_info(url, download=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info\n    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper\n    self.report_error(str(e), e.format_traceback())\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error\n    self.trouble(f\'{self._format_err("ERROR:", self.Styles.ERROR)} {message}\', *args, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble\n    raise DownloadError(message, exc_info)\nyt_dlp.utils.DownloadError: ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n', 'args': "['https://www.tiktok.com/@comiendobienn/video/7518837827455552790']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
[2025-07-05 12:51:47,488: INFO/MainProcess] Task procesar_receta_task[23eb74ea-26a8-48f2-be38-69586e29ac2a] received
[2025-07-05 12:51:47,493: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 12:51:47,907: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[2025-07-05 12:51:48,082: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[2025-07-05 12:51:48,250: WARNING/ForkPoolWorker-14] WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[2025-07-05 12:51:48,418: WARNING/ForkPoolWorker-14] WARNING: [TikTok] 7518837827455552790: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[2025-07-05 12:51:49,406: WARNING/ForkPoolWorker-14] ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:51:49,423: WARNING/ForkPoolWorker-14] --- Logging error ---
[2025-07-05 12:51:49,426: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:51:49,427: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,428: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,429: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,430: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,430: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,431: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1280, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,431: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
[2025-07-05 12:51:49,432: WARNING/ForkPoolWorker-14] yt_dlp.utils.RegexNotFoundError: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:51:49,433: WARNING/ForkPoolWorker-14] 
During handling of the above exception, another exception occurred:
[2025-07-05 12:51:49,433: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:51:49,434: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,435: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,435: WARNING/ForkPoolWorker-14]   File "/usr/src/app/worker.py", line 20, in procesar_receta_task
    procesar_receta(url)
[2025-07-05 12:51:49,435: WARNING/ForkPoolWorker-14]   File "/usr/src/app/model_mistral_tiktok.py", line 105, in procesar_receta
    titulo, descripcion, thumbnail = download_tiktok_video(url, f'./videos/video{timestamp}.mp4')
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,436: WARNING/ForkPoolWorker-14]   File "/usr/src/app/model_mistral_tiktok.py", line 33, in download_tiktok_video
    info = ydl.extract_info(url, download=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,437: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,437: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    self.report_error(str(e), e.format_traceback())
[2025-07-05 12:51:49,438: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
[2025-07-05 12:51:49,438: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble
    raise DownloadError(message, exc_info)
[2025-07-05 12:51:49,438: WARNING/ForkPoolWorker-14] yt_dlp.utils.DownloadError: ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2025-07-05 12:51:49,439: WARNING/ForkPoolWorker-14] 
During handling of the above exception, another exception occurred:
[2025-07-05 12:51:49,439: WARNING/ForkPoolWorker-14] Traceback (most recent call last):
[2025-07-05 12:51:49,440: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,440: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,441: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
          ^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,441: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 695, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,442: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
    r = super().formatException(ei)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,442: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/logging/__init__.py", line 645, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2025-07-05 12:51:49,443: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,443: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 690, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,443: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
[2025-07-05 12:51:49,443: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,444: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/traceback.py", line 366, in _get_code_position
    positions_gen = code.co_positions()
                    ^^^^^^^^^^^^^^^^^
[2025-07-05 12:51:49,444: WARNING/ForkPoolWorker-14] AttributeError: '_Code' object has no attribute 'co_positions'
[2025-07-05 12:51:49,445: WARNING/ForkPoolWorker-14] Call stack:
[2025-07-05 12:51:49,447: WARNING/ForkPoolWorker-14]   File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
[2025-07-05 12:51:49,447: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
[2025-07-05 12:51:49,447: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
[2025-07-05 12:51:49,448: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
[2025-07-05 12:51:49,448: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
[2025-07-05 12:51:49,449: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-07-05 12:51:49,450: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-07-05 12:51:49,450: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
[2025-07-05 12:51:49,451: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-07-05 12:51:49,452: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2025-07-05 12:51:49,452: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
    worker.start()
[2025-07-05 12:51:49,452: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2025-07-05 12:51:49,452: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-07-05 12:51:49,453: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-07-05 12:51:49,453: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2025-07-05 12:51:49,453: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-07-05 12:51:49,454: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-07-05 12:51:49,454: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2025-07-05 12:51:49,455: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
    return super()._create_worker_process(i)
[2025-07-05 12:51:49,455: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2025-07-05 12:51:49,456: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2025-07-05 12:51:49,456: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2025-07-05 12:51:49,456: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2025-07-05 12:51:49,457: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2025-07-05 12:51:49,457: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2025-07-05 12:51:49,457: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2025-07-05 12:51:49,458: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-07-05 12:51:49,458: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-07-05 12:51:49,459: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-07-05 12:51:49,459: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
[2025-07-05 12:51:49,460: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(
[2025-07-05 12:51:49,460: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
[2025-07-05 12:51:49,461: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
    self._log_error(task, req, einfo)
[2025-07-05 12:51:49,461: WARNING/ForkPoolWorker-14]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
    logger.log(policy.severity, policy.format.strip(), context,
[2025-07-05 12:51:49,461: WARNING/ForkPoolWorker-14] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
Arguments: {'hostname': 'celery@0d4ba274b8e1', 'id': '23eb74ea-26a8-48f2-be38-69586e29ac2a', 'name': 'procesar_receta_task', 'exc': "DownloadError('ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper\n    return func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info\n    ie_result = ie.extract(url)\n                ^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract\n    ie_result = self._real_extract(url)\n                ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract\n    sigi_data = self._get_sigi_state(webpage, video_id)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state\n    return self._search_json(\n           ^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1280, in _search_json\n    json_string = self._search_regex(\n                  ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex\n    raise RegexNotFoundError(\'Unable to extract %s\' % _name)\nyt_dlp.utils.RegexNotFoundError: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/worker.py", line 20, in procesar_receta_task\n    procesar_receta(url)\n  File "/usr/src/app/model_mistral_tiktok.py", line 105, in procesar_receta\n    titulo, descripcion, thumbnail = download_tiktok_video(url, f\'./videos/video{timestamp}.mp4\')\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/model_mistral_tiktok.py", line 33, in download_tiktok_video\n    info = ydl.extract_info(url, download=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info\n    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper\n    self.report_error(str(e), e.format_traceback())\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error\n    self.trouble(f\'{self._format_err("ERROR:", self.Styles.ERROR)} {message}\', *args, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble\n    raise DownloadError(message, exc_info)\nyt_dlp.utils.DownloadError: ERROR: [TikTok] 7518837827455552790: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n', 'args': "['https://www.tiktok.com/@comiendobienn/video/7518837827455552790']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
[2025-07-05 14:23:26,640: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 14:23:26,642: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 14:23:27,648: INFO/MainProcess] mingle: all alone
[2025-07-05 14:23:27,657: INFO/MainProcess] celery@bb7916c1c002 ready.
[2025-07-05 14:23:29,389: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 14:26:38,744: INFO/MainProcess] Task procesar_receta_task[830e5419-b849-48b8-9f69-ac314bc13ddf] received
[2025-07-05 14:26:38,745: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 14:26:40,887: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at   69.80KiB/s ETA 00:31
[2025-07-05 14:26:40,887: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  197.47KiB/s ETA 00:11
[2025-07-05 14:26:40,888: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at  439.14KiB/s ETA 00:05
[2025-07-05 14:26:40,889: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at  891.46KiB/s ETA 00:02
[2025-07-05 14:26:40,890: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    1.71MiB/s ETA 00:01
[2025-07-05 14:26:40,896: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    2.60MiB/s ETA 00:00
[2025-07-05 14:26:40,916: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    2.81MiB/s ETA 00:00
[2025-07-05 14:26:40,953: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    3.09MiB/s ETA 00:00
[2025-07-05 14:26:40,993: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at    4.11MiB/s ETA 00:00
[2025-07-05 14:26:41,062: WARNING/ForkPoolWorker-14] [download]  46.0% of    2.17MiB at    5.25MiB/s ETA 00:00
[2025-07-05 14:26:41,194: WARNING/ForkPoolWorker-14] [download]  92.0% of    2.17MiB at    6.21MiB/s ETA 00:00
[2025-07-05 14:26:41,231: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at    6.05MiB/s ETA 00:00
[2025-07-05 14:26:41,235: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:00 at 4.62MiB/s   
[2025-07-05 14:26:41,236: WARNING/ForkPoolWorker-14]                                                       
[2025-07-05 14:26:41,240: WARNING/ForkPoolWorker-14] 🎵 Descargando solo audio...
[2025-07-05 14:26:41,953: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at   72.99KiB/s ETA 00:30
[2025-07-05 14:26:41,954: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  208.53KiB/s ETA 00:10
[2025-07-05 14:26:41,955: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at  465.89KiB/s ETA 00:04
[2025-07-05 14:26:41,955: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at  951.16KiB/s ETA 00:02
[2025-07-05 14:26:41,980: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at  763.06KiB/s ETA 00:02
[2025-07-05 14:26:41,998: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    1.06MiB/s ETA 00:01
[2025-07-05 14:26:42,021: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    1.52MiB/s ETA 00:01
[2025-07-05 14:26:42,052: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    2.21MiB/s ETA 00:00
[2025-07-05 14:26:42,083: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at    3.48MiB/s ETA 00:00
[2025-07-05 14:26:42,149: WARNING/ForkPoolWorker-14] [download]  46.0% of    2.17MiB at    4.77MiB/s ETA 00:00
[2025-07-05 14:26:42,270: WARNING/ForkPoolWorker-14] [download]  92.0% of    2.17MiB at    6.05MiB/s ETA 00:00
[2025-07-05 14:26:42,296: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at    6.10MiB/s ETA 00:00
[2025-07-05 14:26:42,301: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:00 at 5.13MiB/s   
[2025-07-05 14:26:42,301: WARNING/ForkPoolWorker-14]                                                       
[2025-07-05 14:26:42,305: WARNING/ForkPoolWorker-14] 🧠 Transcribiendo con Whisper local...
[2025-07-05 14:26:42,307: WARNING/ForkPoolWorker-14] /usr/local/lib/python3.11/site-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

[2025-07-05 15:41:35,741: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 15:41:35,744: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 15:41:36,750: INFO/MainProcess] mingle: all alone
[2025-07-05 15:41:36,759: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 15:41:38,087: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 15:48:29,598: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 15:48:29,600: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 15:48:30,606: INFO/MainProcess] mingle: all alone
[2025-07-05 15:48:30,615: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 15:48:31,822: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 15:50:59,119: INFO/MainProcess] Task create_task[5a94235c-a9cd-4bf0-89c2-667f8a00f115] received
[2025-07-05 15:51:09,126: INFO/ForkPoolWorker-14] Task create_task[5a94235c-a9cd-4bf0-89c2-667f8a00f115] succeeded in 10.00555851000172s: True
[2025-07-05 15:52:35,426: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 15:52:35,429: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 15:52:36,435: INFO/MainProcess] mingle: all alone
[2025-07-05 15:52:36,444: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 15:52:36,572: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 15:53:10,617: INFO/MainProcess] Task procesar_receta_task[1bf8733a-e3a4-43dd-9c02-6abca45dd38e] received
[2025-07-05 15:53:10,618: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 15:53:12,141: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  302.47KiB/s ETA 00:07
[2025-07-05 15:53:12,142: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  721.54KiB/s ETA 00:03
[2025-07-05 15:53:12,142: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at    1.40MiB/s ETA 00:01
[2025-07-05 15:53:12,143: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    2.57MiB/s ETA 00:00
[2025-07-05 15:53:12,144: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    4.44MiB/s ETA 00:00
[2025-07-05 15:53:12,159: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    2.86MiB/s ETA 00:00
[2025-07-05 15:53:12,180: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    2.89MiB/s ETA 00:00
[2025-07-05 15:53:12,895: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at  336.69KiB/s ETA 00:05
[2025-07-05 15:53:12,898: WARNING/ForkPoolWorker-14] [download]  19.5% of    2.17MiB at  570.77KiB/s ETA 00:03
[2025-07-05 15:53:14,305: WARNING/ForkPoolWorker-14] [download]  35.6% of    2.17MiB at  365.59KiB/s ETA 00:03
[2025-07-05 15:53:14,929: WARNING/ForkPoolWorker-14] [download]  47.1% of    2.17MiB at  375.11KiB/s ETA 00:03
[2025-07-05 15:53:15,790: WARNING/ForkPoolWorker-14] [download]  65.4% of    2.17MiB at  398.48KiB/s ETA 00:01
[2025-07-05 15:53:16,215: WARNING/ForkPoolWorker-14] [download]  86.7% of    2.17MiB at  473.25KiB/s ETA 00:00
[2025-07-05 15:53:16,384: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at  523.86KiB/s ETA 00:00
[2025-07-05 15:53:16,389: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:04 at 510.34KiB/s 
[2025-07-05 15:53:16,390: WARNING/ForkPoolWorker-14]                                                         
[2025-07-05 15:53:16,393: WARNING/ForkPoolWorker-14] 🎵 Descargando solo audio...
[2025-07-05 15:53:17,204: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  453.24KiB/s ETA 00:04
[2025-07-05 15:53:17,204: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at    1.00MiB/s ETA 00:02
[2025-07-05 15:53:17,205: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at    1.88MiB/s ETA 00:01
[2025-07-05 15:53:17,206: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    3.30MiB/s ETA 00:00
[2025-07-05 15:53:17,268: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at  465.44KiB/s ETA 00:04
[2025-07-05 15:53:17,475: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at  230.29KiB/s ETA 00:09
[2025-07-05 15:53:17,797: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at  213.28KiB/s ETA 00:09
[2025-07-05 15:53:18,618: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at  180.06KiB/s ETA 00:10
[2025-07-05 15:53:18,682: WARNING/ForkPoolWorker-14] [download]  18.5% of    2.17MiB at  277.61KiB/s ETA 00:06
[2025-07-05 15:53:19,043: WARNING/ForkPoolWorker-14] [download]  32.5% of    2.17MiB at  392.48KiB/s ETA 00:03
[2025-07-05 15:53:19,210: WARNING/ForkPoolWorker-14] [download]  60.5% of    2.17MiB at  670.46KiB/s ETA 00:01
[2025-07-05 15:53:19,933: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at  814.45KiB/s ETA 00:00
[2025-07-05 15:53:19,937: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:02 at 782.62KiB/s 
[2025-07-05 15:53:19,937: WARNING/ForkPoolWorker-14]                                                         
[2025-07-05 15:53:19,941: WARNING/ForkPoolWorker-14] 🧠 Transcribiendo con Whisper local...
[2025-07-05 15:53:19,943: WARNING/ForkPoolWorker-14] /usr/local/lib/python3.11/site-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

[2025-07-05 17:24:33,372: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 17:24:33,376: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 17:24:34,383: INFO/MainProcess] mingle: all alone
[2025-07-05 17:24:34,393: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 17:24:37,792: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 17:25:04,259: INFO/MainProcess] Task procesar_receta_task[799831bf-d59a-4575-a64c-55bce05bf098] received
[2025-07-05 17:25:04,261: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 17:25:05,793: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  129.87KiB/s ETA 00:17
[2025-07-05 17:25:05,794: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  351.92KiB/s ETA 00:06
[2025-07-05 17:25:05,794: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at  754.41KiB/s ETA 00:02
[2025-07-05 17:25:05,795: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    1.45MiB/s ETA 00:01
[2025-07-05 17:25:05,796: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    2.78MiB/s ETA 00:00
[2025-07-05 17:25:05,803: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    3.34MiB/s ETA 00:00
[2025-07-05 17:25:05,826: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    3.01MiB/s ETA 00:00
[2025-07-05 17:25:05,849: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    3.87MiB/s ETA 00:00
[2025-07-05 17:25:05,883: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at    5.11MiB/s ETA 00:00
[2025-07-05 17:25:05,937: WARNING/ForkPoolWorker-14] [download]  46.0% of    2.17MiB at    6.58MiB/s ETA 00:00
[2025-07-05 17:25:06,042: WARNING/ForkPoolWorker-14] [download]  92.0% of    2.17MiB at    7.78MiB/s ETA 00:00
[2025-07-05 17:25:06,064: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at    7.78MiB/s ETA 00:00
[2025-07-05 17:25:06,068: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:00 at 5.58MiB/s   
[2025-07-05 17:25:06,069: WARNING/ForkPoolWorker-14]                                                       
[2025-07-05 17:25:06,072: WARNING/ForkPoolWorker-14] 🎵 Descargando solo audio...
[2025-07-05 17:25:06,857: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  297.13KiB/s ETA 00:07
[2025-07-05 17:25:06,858: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  727.97KiB/s ETA 00:03
[2025-07-05 17:25:06,858: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at    1.40MiB/s ETA 00:01
[2025-07-05 17:25:06,859: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    2.59MiB/s ETA 00:00
[2025-07-05 17:25:06,860: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    4.74MiB/s ETA 00:00
[2025-07-05 17:25:06,871: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    3.53MiB/s ETA 00:00
[2025-07-05 17:25:06,887: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    3.70MiB/s ETA 00:00
[2025-07-05 17:25:06,914: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    4.10MiB/s ETA 00:00
[2025-07-05 17:25:06,939: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at    5.86MiB/s ETA 00:00
[2025-07-05 17:25:07,002: WARNING/ForkPoolWorker-14] [download]  46.0% of    2.17MiB at    6.73MiB/s ETA 00:00
[2025-07-05 17:25:07,106: WARNING/ForkPoolWorker-14] [download]  92.0% of    2.17MiB at    7.91MiB/s ETA 00:00
[2025-07-05 17:25:07,146: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at    7.43MiB/s ETA 00:00
[2025-07-05 17:25:07,150: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:00 at 6.05MiB/s   
[2025-07-05 17:25:07,150: WARNING/ForkPoolWorker-14]                                                       
[2025-07-05 17:25:07,154: WARNING/ForkPoolWorker-14] 🧠 Transcribiendo con Whisper local...
[2025-07-05 17:25:07,157: WARNING/ForkPoolWorker-14] /usr/local/lib/python3.11/site-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

[2025-07-05 17:27:13,760: INFO/MainProcess] Task create_task[ac1fcad4-8028-4ef6-b888-ca140b17f113] received
[2025-07-05 17:27:23,764: INFO/ForkPoolWorker-15] Task create_task[ac1fcad4-8028-4ef6-b888-ca140b17f113] succeeded in 10.002537173000007s: True
[2025-07-05 17:43:56,067: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 17:43:56,070: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 17:43:57,077: INFO/MainProcess] mingle: all alone
[2025-07-05 17:43:57,085: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 17:43:57,452: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 17:44:10,286: INFO/MainProcess] Task procesar_receta_task[4f311aec-309b-4584-b873-87cc34cc96c4] received
[2025-07-05 17:44:10,288: WARNING/ForkPoolWorker-14] ⏬ Descargando vídeo...
[2025-07-05 17:44:11,781: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  308.50KiB/s ETA 00:07
[2025-07-05 17:44:11,782: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  728.68KiB/s ETA 00:03
[2025-07-05 17:44:11,783: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at    1.39MiB/s ETA 00:01
[2025-07-05 17:44:11,784: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    2.54MiB/s ETA 00:00
[2025-07-05 17:44:11,784: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    4.59MiB/s ETA 00:00
[2025-07-05 17:44:11,799: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    2.88MiB/s ETA 00:00
[2025-07-05 17:44:11,819: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    2.97MiB/s ETA 00:00
[2025-07-05 17:44:11,848: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    3.54MiB/s ETA 00:00
[2025-07-05 17:44:12,831: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at  485.40KiB/s ETA 00:03
[2025-07-05 17:44:19,237: WARNING/ForkPoolWorker-14] [download]  34.7% of    2.17MiB at  103.44KiB/s ETA 00:14
[2025-07-05 17:44:19,238: WARNING/ForkPoolWorker-14] [download]  40.5% of    2.17MiB at  120.88KiB/s ETA 00:10
[2025-07-05 17:44:19,442: WARNING/ForkPoolWorker-14] [download]  52.2% of    2.17MiB at  151.67KiB/s ETA 00:07
[2025-07-05 17:44:20,153: WARNING/ForkPoolWorker-14] [download]  75.7% of    2.17MiB at  201.01KiB/s ETA 00:02
[2025-07-05 17:44:20,386: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at  258.45KiB/s ETA 00:00
[2025-07-05 17:44:20,390: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:08 at 255.01KiB/s 
[2025-07-05 17:44:20,391: WARNING/ForkPoolWorker-14]                                                         
[2025-07-05 17:44:20,395: WARNING/ForkPoolWorker-14] 🎵 Descargando solo audio...
[2025-07-05 17:44:21,264: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  467.02KiB/s ETA 00:04
[2025-07-05 17:44:21,298: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at   82.98KiB/s ETA 00:26
[2025-07-05 17:44:21,299: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at  188.17KiB/s ETA 00:11
[2025-07-05 17:44:21,300: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at  394.32KiB/s ETA 00:05
[2025-07-05 17:44:21,650: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at   79.93KiB/s ETA 00:27
[2025-07-05 17:44:21,652: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at  161.76KiB/s ETA 00:13
[2025-07-05 17:44:22,480: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at  104.27KiB/s ETA 00:20
[2025-07-05 17:44:22,531: WARNING/ForkPoolWorker-14] [download]   9.2% of    2.17MiB at  160.94KiB/s ETA 00:12
[2025-07-05 17:44:22,701: WARNING/ForkPoolWorker-14] [download]  16.1% of    2.17MiB at  249.31KiB/s ETA 00:07
[2025-07-05 17:44:23,985: WARNING/ForkPoolWorker-14] [download]  30.0% of    2.17MiB at  245.28KiB/s ETA 00:06
[2025-07-05 17:44:25,078: WARNING/ForkPoolWorker-14] [download]  40.8% of    2.17MiB at  238.06KiB/s ETA 00:05
[2025-07-05 17:44:26,472: WARNING/ForkPoolWorker-14] [download]  50.7% of    2.17MiB at  216.64KiB/s ETA 00:05
[2025-07-05 17:44:27,143: WARNING/ForkPoolWorker-14] [download]  57.8% of    2.17MiB at  218.78KiB/s ETA 00:04
[2025-07-05 17:44:28,431: WARNING/ForkPoolWorker-14] [download]  68.4% of    2.17MiB at  212.29KiB/s ETA 00:03
[2025-07-05 17:44:29,306: WARNING/ForkPoolWorker-14] [download]  76.6% of    2.17MiB at  211.91KiB/s ETA 00:02
[2025-07-05 17:44:29,709: WARNING/ForkPoolWorker-14] [download]  86.0% of    2.17MiB at  226.53KiB/s ETA 00:01
[2025-07-05 17:44:30,046: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at  253.30KiB/s ETA 00:00
[2025-07-05 17:44:30,050: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:08 at 250.06KiB/s 
[2025-07-05 17:44:30,050: WARNING/ForkPoolWorker-14]                                                         
[2025-07-05 17:44:30,054: WARNING/ForkPoolWorker-14] 🧠 Transcribiendo con Whisper local...
[2025-07-05 17:44:30,055: WARNING/ForkPoolWorker-14] /usr/local/lib/python3.11/site-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

[2025-07-05 17:57:32,655: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 17:57:32,657: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 17:57:33,664: INFO/MainProcess] mingle: all alone
[2025-07-05 17:57:33,673: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 17:57:35,077: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 17:59:40,367: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-07-05 17:59:40,369: INFO/MainProcess] mingle: searching for neighbors
[2025-07-05 17:59:41,376: INFO/MainProcess] mingle: all alone
[2025-07-05 17:59:41,385: INFO/MainProcess] celery@ca25b68cad58 ready.
[2025-07-05 17:59:45,621: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-07-05 17:59:47,855: INFO/MainProcess] Task procesar_receta_task[d84cb68c-3ea0-461f-8eca-aeddb9e4288e] received
[2025-07-05 17:59:49,319: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  282.65KiB/s ETA 00:07
[2025-07-05 17:59:49,319: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at  679.46KiB/s ETA 00:03
[2025-07-05 17:59:49,321: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at    1.20MiB/s ETA 00:01
[2025-07-05 17:59:49,322: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    2.25MiB/s ETA 00:00
[2025-07-05 17:59:49,322: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    4.01MiB/s ETA 00:00
[2025-07-05 17:59:49,336: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    2.90MiB/s ETA 00:00
[2025-07-05 17:59:49,356: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    3.01MiB/s ETA 00:00
[2025-07-05 17:59:49,382: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    3.74MiB/s ETA 00:00
[2025-07-05 17:59:49,411: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at    5.20MiB/s ETA 00:00
[2025-07-05 17:59:49,466: WARNING/ForkPoolWorker-14] [download]  46.0% of    2.17MiB at    6.61MiB/s ETA 00:00
[2025-07-05 17:59:49,586: WARNING/ForkPoolWorker-14] [download]  92.0% of    2.17MiB at    7.37MiB/s ETA 00:00
[2025-07-05 17:59:49,615: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at    7.23MiB/s ETA 00:00
[2025-07-05 17:59:49,619: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:00 at 5.29MiB/s   
[2025-07-05 17:59:49,620: WARNING/ForkPoolWorker-14]                                                       
[2025-07-05 17:59:50,463: WARNING/ForkPoolWorker-14] [download]   0.0% of    2.17MiB at  586.45KiB/s ETA 00:03
[2025-07-05 17:59:50,464: WARNING/ForkPoolWorker-14] [download]   0.1% of    2.17MiB at    1.16MiB/s ETA 00:01
[2025-07-05 17:59:50,465: WARNING/ForkPoolWorker-14] [download]   0.3% of    2.17MiB at    2.02MiB/s ETA 00:01
[2025-07-05 17:59:50,466: WARNING/ForkPoolWorker-14] [download]   0.7% of    2.17MiB at    3.48MiB/s ETA 00:00
[2025-07-05 17:59:50,466: WARNING/ForkPoolWorker-14] [download]   1.4% of    2.17MiB at    6.03MiB/s ETA 00:00
[2025-07-05 17:59:50,484: WARNING/ForkPoolWorker-14] [download]   2.8% of    2.17MiB at    2.73MiB/s ETA 00:00
[2025-07-05 17:59:50,504: WARNING/ForkPoolWorker-14] [download]   5.7% of    2.17MiB at    2.92MiB/s ETA 00:00
[2025-07-05 17:59:50,526: WARNING/ForkPoolWorker-14] [download]  11.5% of    2.17MiB at    3.86MiB/s ETA 00:00
[2025-07-05 17:59:50,551: WARNING/ForkPoolWorker-14] [download]  23.0% of    2.17MiB at    5.59MiB/s ETA 00:00
[2025-07-05 17:59:50,619: WARNING/ForkPoolWorker-14] [download]  46.0% of    2.17MiB at    6.36MiB/s ETA 00:00
[2025-07-05 17:59:50,722: WARNING/ForkPoolWorker-14] [download]  92.0% of    2.17MiB at    7.67MiB/s ETA 00:00
[2025-07-05 17:59:50,743: WARNING/ForkPoolWorker-14] [download] 100.0% of    2.17MiB at    7.71MiB/s ETA 00:00
[2025-07-05 17:59:50,747: WARNING/ForkPoolWorker-14] [download] 100% of    2.17MiB in 00:00:00 at 6.11MiB/s   
[2025-07-05 17:59:50,748: WARNING/ForkPoolWorker-14]                                                       
[2025-07-05 17:59:50,751: WARNING/ForkPoolWorker-14] 🧠 Transcribiendo con Whisper local...
[2025-07-05 17:59:50,753: WARNING/ForkPoolWorker-14] /usr/local/lib/python3.11/site-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

